github:
  client:
    id: b7af8716ce883057c670
    secret: 82d1a0c119edc1b319706749b07857c0ad42f28f
  redirect:
    uri: http://localhost:8080/callback
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
  thymeleaf:
    cache: false